### ISSUE TITLE
$png->interlace_method(); and $png-read_file();

### ISSUE THREAD

**Issue by alanmead** [benkasminbullock/Image-PNG#16]
The POD suggests (in the initial code snippet) that there is a method "read_file()" but the method is apparently just "read()". The POD also described a method "interlace_method()" but there is no such function. $png->interlace_type() seems to be defined, but doesn't work:

```
use strict;
use warnings;
use Image::PNG;

my $png = Image::PNG->new ();
my $fn = shift or die;
$png->read($fn);
printf "interlacing method = %d\n", $png->interlace_type();
```
produces:
`Can't locate object method "interlace_type" via package "Image::PNG" at ./test_png.pl line 15.`

**Comment by benkasminbullock** [comment]
The method's name was "interlacing_method()" in the documentation. I've implemented this method as of commit ddd4a5ff61dc35830859846754cd091ba4491fc1 and the error in the documentation you kindly pointed out is also corrected. The corrected Image::PNG is now uploaded to CPAN as version 0.24.

Thank you for this bug report. I'm closing this issue now but if you are not satisfied with this response, please reopen it.
